"""L6 投資主題對照（靜態表，可逐步擴充）。"""

from __future__ import annotations

# stock_id -> theme code（用於 L3 輪動矩陣）
THEME_BY_STOCK: dict[str, str] = {
    # AI 鏈
    "2330": "AI_SEMIS",
    "2303": "AI_SEMIS",
    "2344": "AI_SEMIS",
    "2337": "AI_SEMIS",
    "6488": "AI_SEMIS",
    "5347": "AI_SEMIS",
    "2454": "AI_SEMIS",
    "3443": "AI_SEMIS",
    "3661": "AI_SEMIS",
    "5274": "AI_SEMIS",
    "3037": "AI_SEMIS",
    "3711": "ADV_PACKAGING",
    "2449": "ADV_PACKAGING",
    "6147": "ADV_PACKAGING",
    "2317": "AI_SERVER",
    "2376": "AI_SERVER",
    "2382": "AI_SERVER",
    "3231": "AI_SERVER",
    "6669": "AI_SERVER",
    "3017": "AI_COOLING",
    "8996": "AI_COOLING",
    "2308": "AI_POWER",
    "2301": "AI_POWER",
    "2368": "AI_POWER",
    "2383": "AI_POWER",
    "2345": "AI_NETWORK",
    "6223": "SEMI_EQUIP",
    "3583": "SEMI_EQUIP",
    "3131": "SEMI_EQUIP",
    "6510": "SEMI_EQUIP",
    "2408": "MEMORY",
    "2345": "MEMORY",
    "8299": "MEMORY",
    "3008": "MOBILE_OPTICS",
    "4966": "MOBILE_OPTICS",
    # 傳產 / 景氣
    "1303": "CYCLE_CHEM",
    "6505": "CYCLE_CHEM",
    "2002": "CYCLE_STEEL",
    # 金融
    "2881": "FINANCIAL",
    "2882": "FINANCIAL",
    "2883": "FINANCIAL",
    "2884": "FINANCIAL",
    "2885": "FINANCIAL",
    "2886": "FINANCIAL",
    "2887": "FINANCIAL",
    "2890": "FINANCIAL",
    "2891": "FINANCIAL",
    "2892": "FINANCIAL",
    "5880": "FINANCIAL",
    # 防禦 / 公用
    "2412": "DEFENSIVE_TELCO",
    "4904": "DEFENSIVE_TELCO",
    "3045": "DEFENSIVE_TELCO",
    # 其他科技
    "2451": "PC_COMPONENT",
    "2327": "PASSIVE",
    "3044": "PCB",
    "2360": "TEST_EQUIP",
    "3653": "COOLING",
    "6805": "COOLING",
    "7769": "COOLING",
    "8046": "PCB",
    "3081": "OPTICS",
    "3105": "COMPOUND_SEMI",
    "3189": "PACKAGING",
    "3264": "IC_DESIGN",
    "3529": "IP",
    "3665": "CONNECTOR",
    "4958": "FPC",
    "6274": "CCL",
    "6515": "TEST_SOCKET",
    "8358": "CCL",
    "1216": "CONSUMER",
    "2059": "HARDWARE",
    "2603": "SHIPPING",
}

THEME_LABEL: dict[str, str] = {
    "AI_SEMIS": "AI半導體",
    "AI_SERVER": "AI伺服器",
    "AI_COOLING": "AI散熱",
    "AI_POWER": "AI電源",
    "AI_NETWORK": "AI網通",
    "ADV_PACKAGING": "先進封裝",
    "SEMI_EQUIP": "半導體設備",
    "MEMORY": "記憶體",
    "MOBILE_OPTICS": "手機光學",
    "CYCLE_CHEM": "景氣化學",
    "CYCLE_STEEL": "景氣鋼鐵",
    "FINANCIAL": "金融",
    "DEFENSIVE_TELCO": "防禦電信",
    "PC_COMPONENT": "PC零組件",
    "PASSIVE": "被動元件",
    "PCB": "PCB",
    "TEST_EQUIP": "測試設備",
    "COOLING": "散熱",
    "OPTICS": "光通訊",
    "COMPOUND_SEMI": "化合物半導體",
    "PACKAGING": "封測",
    "IC_DESIGN": "IC設計",
    "IP": "IP矽智財",
    "CONNECTOR": "連接器",
    "FPC": "軟板",
    "CCL": "銅箔基板",
    "TEST_SOCKET": "測試介面",
    "CONSUMER": "消費",
    "HARDWARE": "零組件",
    "SHIPPING": "航運",
    "UNKNOWN": "未分類",
}


def stock_theme(stock_id: str) -> str:
    return THEME_BY_STOCK.get(stock_id, "UNKNOWN")


def theme_label(theme_code: str) -> str:
    return THEME_LABEL.get(theme_code, theme_code)
